# GitHub Actions workflow for deploying CloudWatch alarms to AWS

name: Deploy Alarms to AWS

on:
  # Trigger manually or on push/pull to main branch
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy CloudWatch Alarms
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Make deployment script executable
        run: chmod +x ./deploy_luglink_alarms.sh

      - name: Deploy alarms to AWS
        run: ./deploy_luglink_alarms.sh
